# Generated by Django 5.2.5 on 2025-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('essay_prompt', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Scholarships',
            },
        ),
    ]
