# Generated by Django 5.2.1 on 2025-09-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='provider',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
