# Generated by Django 5.2.1 on 2025-09-01 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scholarships_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='institution',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
