# Generated by Django 5.2.5 on 2025-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scholarships_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
