# Generated by Django 5.2.5 on 2025-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scholarships_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=20250101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarships',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='essay_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
