# Generated by Django 5.2.5 on 2025-09-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_scholarships_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
