# Generated by Django 5.2.5 on 2025-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_scholarships_link_alter_scholarships_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
