# Generated by Django 5.2.5 on 2025-09-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
