# Generated by Django 5.2.5 on 2025-09-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_scholarships_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
