# Generated by Django 5.2.5 on 2025-09-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scholarships_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='logo_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
